### ISSUE TITLE
сломался antizapret.pl

### ISSUE THREAD

**Issue by mnshkoff** [Limych/antizapret#2]
OPNsense 20.1.6-amd64
FreeBSD 11.2-RELEASE-p19-HBSD

Скрипт antizapret.pl после выгрузки с api.antizapret.info вылетает с ошибкой
Use of uninitialized value $mask in string eq at antizapret.pl line 14

В перле не силен, побороть не получается.

**Comment by Limych** [comment]
Ох-ты... А я и не знал, что кто-то этим пользуется 😊
Спасибо за наводку. Посмотрю, что можно сделать.

**Comment by Limych** [comment]
Увы, сайт antizapret.info, откуда брались данные, умер...
Обновляем скрипт. Должно всё заработать обратно.
