### ISSUE TITLE
WireGuard support/Поддержка WireGuard

### ISSUE THREAD

**Issue by Gr33nEyes** [Limych/antizapret#5]
Будет ли добавлена поддержка WireGuard?

**Comment by Limych** [comment]
Я добавлять такую поддержку пока не планирую.
Если Вы возьмёте на себя труд сделать PR с добавлением поддержки, я буду рад её добавить.

**Comment by Limych** [comment]
https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html начиная с шага 6
WireGuard создал виртуальный интерфейс wg1 на который и настроен был роутинг через файрволл.

У меня прекрасно работает в связке со скриптом антизапрета.

**Comment by Limych** [comment]
1. INTERFACES > ASSIGNMENTS. Создаём интерфейс для VPN (у меня он зовётся «VPS») и назначаем в него порт WireGuard (у меня это wg1);
1. SYSTEM > GATEWAYS > SINGLE. Создаём гейт для VPN (у меня он зовётся «VPS_GW»). Ставим галочку «Far Gateway». Остальное по-умолчанию;
2. FIREWALL > RULES > LAN. Создаём правило роутинга. Destination: AntiZapret_IPs, Gateway: VPS_GW.
1. Всё.
